FROM centos:7.6.1810
MAINTAINER xuwy

RUN set -ex \
    # 预安装所需组件
    # && echo "nameserver 144.144.144.144" >> /etc/resolv.conf \
    && yum -y install epel-release \
    && yum update -y \
    && yum upgrade -y \
    && yum -y install kde-l10n-Chinese telnet \
    && yum reinstall -y glibc-common \
    && rm -rf /tmp/* \
    && rm -rf /var/cache/yum/* \
    && yum clean all -y \
    && localedef -c -f UTF-8 -i zh_CN zh_CN.UTF-8 \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && yum install -y wget tar libffi-devel zlib-devel bzip2-devel openssl-devel ncurses-devel sqlite-devel readline-devel tk-devel gcc make initscripts \
    && yum install -y mysql-devel postgresql-devel libsasl2-devel gcc-c++ libaio git xml2 libxml2-devel curl curl-devel pandoc libjpeg-devel \
    && yum install -y locales java-1.8.0-openjdk java-1.8.0-openjdk-devel libcurl-devel \
    && yum install -y openssl098e supervisor passwd hiredis-devel libsodium-devel \
    && yum install -y redis \
    && yum install -y R

ENV LANG=zh_CN.UTF-8 \
    LANGUAGE=zh_CN:zh \
    LC_ALL=zh_CN.UTF-8

RUN R -e "install.packages(c('shiny', 'rmarkdown', 'devtools', 'RJDBC', 'dplyr', 'plotly', 'RPostgreSQL', 'lubridate', 'DT', 'shinydashboard', 'shinyWidgets', 'readr', 'RMySQL', 'stringr', 'reshape2', 'xts', 'htmlwidgets', 'digest', 'scales', 'ggplot2', 'shinyjs', 'shinyBS', 'forecast', 'tools', 'readr', 'shinyalert', 'shinyAce', 'yaml', 'foreach', 'DescTools', 'Hmisc', 'entropy', 'overlapping', 'jsonlite', 'log4r', 'plumber', 'RCurl', 'uuid', 'future', 'factoextra', 'parallel', 'redux', 'car', 'MASS', 'ggfortify', 'data.table', 'psych', 'ggcorrplot', 'GGally', 'treemap', 'treemapify', 'networkD3', 'flexdashboard', 'pander', 'sodium', 'ggmosaic', 'sjPlot', 'sjmisc', 'sjlabelled', 'servr', 'imputeTS', 'influxdbr', 'config'), repos = 'https://cran.rstudio.com/')"

#-----------------------
# Install pandoc
RUN wget https://github.com/jgm/pandoc/releases/download/2.9.1.1/pandoc-2.9.1.1-linux-amd64.tar.gz \
    && tar -xvf pandoc-2.9.1.1-linux-amd64.tar.gz -C /root/ \
    && rm -rf /usr/bin/pandoc  \
    && ln -s /root/pandoc-2.9.1.1/bin/pandoc /usr/bin/pandoc  \
    && rm -rf pandoc-2.9.1.1-linux-amd64.tar.gz

#-----------------------
# Install Shiny server:
RUN wget https://download3.rstudio.org/centos6.3/x86_64/shiny-server-1.5.13.944-x86_64.rpm \
	&& yum -y install --nogpgcheck shiny-server-1.5.13.944-x86_64.rpm \
	&& rm -rf shiny-server-1.5.13.944-x86_64.rpm \
	&& mkdir -p /var/log/shiny-server \
	&& chown shiny:shiny /var/log/shiny-server \
	&& chown shiny:shiny -R /srv/shiny-server \
	&& chmod 755 -R /srv/shiny-server

EXPOSE 3838 8211

