##############################################
# 基于centos7构建 python37 环境
# 安装Oracle客户端
# airflow相关依赖镜像
##############################################
FROM centos:7
MAINTAINER xuwy

ARG PIP_VERSION="19.0.2"
ENV AIRFLOW_HOME=/home/airflow

COPY dockerSrc/oracle-instantclient12.1 /oracle-instantclient12.1

RUN set -ex \
    # 预安装所需组件
    && yum install -y wget tar libffi-devel zlib-devel bzip2-devel openssl-devel ncurses-devel sqlite-devel readline-devel tk-devel gcc make initscripts \
    && yum install -y mysql mysql-devel postgresql-devel libsasl2-devel openldap-devel gcc-c++ libaio \
    # 安装Python-3.7.0
    && wget https://www.python.org/ftp/python/3.7.0/Python-3.7.0.tgz \
    && tar -zxvf Python-3.7.0.tgz \
    && cd Python-3.7.0 \
    && ./configure prefix=/usr/local/python3 \
    && make \
    && make install \
    && make clean \
    && cd / \
    && rm -rf /Python-3.7.0* \
    && yum install -y epel-release \
    && yum install -y python-pip \
    # 备份旧版本python
    && mv /usr/bin/python /usr/bin/python27 \
    && mv /usr/bin/pip /usr/bin/pip-python2.7 \
    # 配置默认为python3
    && ln -s /usr/local/python3/bin/python3.7 /usr/bin/python \
    && ln -s /usr/local/python3/bin/pip3 /usr/bin/pip \
    # 修复因修改python版本导致yum失效问题
    && sed -i "s#/usr/bin/python#/usr/bin/python2.7#" /usr/bin/yum \
    && sed -i "s#/usr/bin/python#/usr/bin/python2.7#" /usr/libexec/urlgrabber-ext-down \
    && yum install -y deltarpm \
    # 安装 oracle-instantclient
    && rpm -ivh /oracle-instantclient12.1/oracle-instantclient12.1-basic-12.1.0.2.0-1.x86_64.rpm \
    && rpm -ivh /oracle-instantclient12.1/oracle-instantclient12.1-devel-12.1.0.2.0-1.x86_64.rpm \
    && echo 'export ORACLE_HOME=/usr/lib/oracle/12.1/client64' >> /etc/profile \
    && echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ORACLE_HOME:$ORACLE_HOME/lib' >> /etc/profile \
    && echo 'export PATH=$PATH:/usr/local/python3/bin' >> /root/.bashrc \
    && echo 'export ORACLE_HOME=/usr/lib/oracle/12.1/client64' >> /root/.bashrc \
    && echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ORACLE_HOME:$ORACLE_HOME/lib' >> /root/.bashrc \
    && echo 'export PATH=$PATH:/usr/local/python3/bin' >> /etc/profile \
    && source /etc/profile \
    # 修改系统时区为东八区
    && rm -rf /etc/localtime \
    && ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && yum install -y vim \
    # 安装定时任务组件
    && yum -y install cronie \
    # 支持中文
    && yum install kde-l10n-Chinese -y \
    && localedef -c -f UTF-8 -i zh_CN zh_CN.utf8 \
    # 更新pip版本
    && pip install --upgrade pip==${PIP_VERSION} \
    && rm -rf /Python-3.7.0.tgz \
    && rm -rf /oracle-instantclient12.1  \
    # 安装airflow
    && pip install apache-airflow[async,mysql,postgres,oracle,redis,ssh,statsd,virtualenv]==1.10.10 --constraint https://raw.githubusercontent.com/apache/airflow/1.10.10/requirements/requirements-python3.7.txt \
    && pip install flask_bcrypt \
    && pip install pymssql
    
ENV LC_ALL zh_CN.UTF-8

CMD ["python"]
